### ISSUE TITLE
Part 1.1: Explore New Feeds

### ISSUE THREAD

**Issue by ykomal** [Egnite-git/ds-python-du-noelakkidas#1]

**Comment by noelakkidas** [comment]
I have chosen Exploratory data analysis on UBER stocks.
I am going to perform EDA on this data set using a heatmap(2d representation which shows how a variable is correlated with another variable)
the attributes I have chosen are = closing price, opening price, high and low prices.
the main attribute is volume.
I am going to see the correlations between volume and other attributes so that I can know which attribute has a strong correlation with volume and how it is impacting buying and selling.
